language: ruby
rvm:
 - 2.4.0
 - jruby
 - rbx-2

 notifications:
  email: false
  slack: engineering2017:cBFA6v1oFyvJrBXguR4g5pHt
# uncomment and edit the following line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
