# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fda3b1f07ea1f5491acf4ce55c0176b0ca58e3bd5457a4b343341d383d0dfebea095c53320222db31a3c95e444169d9465f656d0abc513ccce7adcb5787820cf


# THIS IS A TEST TO SEE IF GIT WILL IGNORE THIS ********************************


test:
  secret_key_base: 069950c41b882a9b0014297512da346da502d976a2f0c950e61437894019c80d9304491383432677e76165e322faf521452b6a9eadca70a7791b1c93574e3eed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
